# Generated by Django 4.2.4 on 2023-09-13 03:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quality',
            field=models.CharField(default='default_quality', max_length=7),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.TextField(default='default_quality'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
